version: '3.4'

services:
  stack.test.client.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44350
    ports:
      - "53251:80"
      - "44350:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  stack.test.client.blazorapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 4000:80